name: Rust - Supply chain
on:
    # Check whenever a file that affects Rust and its dependencies is changed in a pull request
    pull_request:
        paths:
            - .github/workflows/rust-supply-chain.yml
            - deny.toml
            - '**/Cargo.toml'
            - Cargo.lock
            - '**/*.rs'
    # Check if requested manually from the Actions tab
    workflow_dispatch:
jobs:
    check-formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run cargo deny
              uses: EmbarkStudios/cargo-deny-action@v1
              with:
                log-level: warn
                # TODO: Check everything, or at least more. But until we have fixed some licensing
                # issues we have to check this subset.
                command: check advisories sources bans
